### ISSUE TITLE
new message indicator should be in a straight line

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#11]
It is easy to see how many new messages that i have missed but it would look much better if those  indicators was in a straight line instead of the end of the hub/user name. The hub/nick name will be truncated if it is too long so it must be easy to get that indicator a static position.

![picpick-2015 11 19-21 04 14](https://cloud.githubusercontent.com/assets/5789283/11283041/e51520f8-8f02-11e5-9210-3faa4970f445.jpg)

**Comment by Sopor-** [comment]
This seems to be added already?

**Comment by maksis** [comment]
Uhm I haven't even made commits after you reported the issue..... please don't make bug reports without version and browser information
