### ISSUE TITLE
no space left for the message indicator if the user have a long nick

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#12]
no space left for the message indicator if the user have a long nick or have different nick in each hub

![picpick-2015 11 19-21 20 12](https://cloud.githubusercontent.com/assets/5789283/11283174/b23a3118-8f03-11e5-8851-b34a64b7716f.jpg)

**Comment by maksis** [comment]
Is the label actually missing when it should be shown or is this just an assumption?

**Comment by Sopor-** [comment]
I haven't got any message yet from a user with so long nick as i show in the picture but if i look at the space i can see it won't fit. Have you tested it?

**Comment by Sopor-** [comment]
It seems to move so there will be space for the message indicator...
