### ISSUE TITLE
a few seconds ago

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#15]
It doesn't look nice when the last refresh is below one minute...

Web UI version: 0.3.1

![picpick-2015 11 30-21 06 11](https://cloud.githubusercontent.com/assets/5789283/11483085/d250bd9a-97a6-11e5-940a-24efb57b5e58.jpg)

**Comment by maksis** [comment]
In which way it "doesn't look nice"?

**Comment by Sopor-** [comment]
When there are no margins, but if you think it look nice to have the 'o' so close to the scrollbar you don't need to change anything.
