### ISSUE TITLE
add support for http://username:password@hostname:port

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#16]
It would be nice if i could use http://username:password@hostname:port when i login. I have tried several web browsers and some of them will not ask me to save the password. I have tried both http and https because i know https sometimes not let you save the password but i still not get it to ask me to save the login and password.
The only browser i can get it to work in is Firefox.

**Comment by maksis** [comment]
Are you able to find out that what's needed to make them ask about saving the password? Extra URL parameters shouldn't be implemented because of that.

**Comment by Sopor-** [comment]
it is strange that other sites ask me if i want to save the password...

**Comment by maksis** [comment]
I don't think that it's strange and that's why I asked if you can find out that what needs to be changed to make browsers show the prompt. I'm busy with other things and not going to take a look into it soon but feel to open a new bug report for it.

**Comment by Sopor-** [comment]
You told me that this is working for you so i see it strange that it won't work for me but it work for you when we use the same web browser.

**Comment by Sopor-** [comment]
http://stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password

**Comment by maksis** [comment]
Try the latest version

**Comment by Sopor-** [comment]
still nothing about saving password :(
