### ISSUE TITLE
busy spinning wheel in open filelists...

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#20]
If i have full filelists open and do a reload in the client (from the tab menu) it seems that the Webui can't handle it and only show this spinning busy wheel.

Application version: AirDC++ 3.10a-104-g86c30 x86-64 / 0.850
Web UI version: 0.5.0

**Comment by maksis** [comment]
There should be always a text under the wheel telling what it's doing. See if this still happens with the latest version.

**Comment by maksis** [comment]
Hopefully fixed in 0.6.3
