### ISSUE TITLE
wrong address when address field is empty

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#22]
when pressing connect without any address, it shows an already connected address in the error message

![picpick-2015 12 15-23 58 40](https://cloud.githubusercontent.com/assets/5789283/11826877/404a473e-a388-11e5-8ac1-9d9f514e5509.jpg)

**Comment by Sopor-** [comment]
It seems to connect to the url to the webui

**Comment by maksis** [comment]
I can't prevent the browser from displaying the address where the notification originated from. You shouldn't be seeing such notification in the first place though, which will be fixed in the next version.
