### ISSUE TITLE
can't use edit/remove in favorit hubs after pressing twice on the name

### ISSUE THREAD

**Issue by Sopor-** [maksis/airdcpp-webclient#5]
When i press on a name in favorite hubs the menu drop down with edit and remove but if i press the name again i can't select anything in this menu because it will close when the mouse is over the menu. To get it to work i need to press another name and now it works until i press twice on a name again.

**Comment by Sopor-** [comment]
Update: It seems to be the same in queue and search

**Comment by maksis** [comment]
I'm not able to reproduce such issues but I may have misunderstood something. Please mention the browser that you are using and Web UI version in all bug reports (and make sure that you always have the latest version installed).

**Comment by Sopor-** [comment]
This bug is fixed in latest version
